version: '3.8'

services:
  web:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
